language: python

python:
    - 2.7
    - 3.4

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.29-1.linux-64.sh
    - sudo sh lilypond-2.19.29-1.linux-64.sh --batch
    - pip install --upgrade pip

install:
    - pip install -e git://github.com/Abjad/abjad.git#egg=abjad
    - pip install -e git://github.com/Abjad/ide.git#egg=ide
    - pip install -e git://github.com/josiah-wolf-oberholtzer/consort.git#egg=consort
    - pip install -e .

script:
    - ajv doctest -x ./trustme
    - py.test -xrf ./trustme
    - python ./trustme/test/test_segments.py

notifications:
    email: false
